name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn commitlint --from=origin/main
        if: github.actor != 'dependabot[bot]'
      - run: yarn lint:all
      - run: yarn dedupe --check
      - run: yarn prettier:check
      - run: yarn fix --check
      - run: yarn tsc
      - run: yarn build:all

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn test:all
